"""Tab: structural report - plain-language assessment (no AI) + PDF export."""
from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QLabel,
                               QPushButton, QTextEdit, QCheckBox, QFileDialog,
                               QMessageBox, QFrame)

from ...core.i18n import t
from ...core.report import summary, pdf_report
from ...core.mass import total_mass
from ...core.loads import resolve_design_point, strip_loads
from ..dialogs import author_html

_CHIP = {
    "green": ("#059669", "#ecfdf5", "#a7f3d0"),
    "yellow": ("#b45309", "#fffbeb", "#fde68a"),
    "red": ("#b91c1c", "#fef2f2", "#fecaca"),
}


class ReportTab(QWidget):
    def __init__(self, app_state):
        super().__init__()
        self.state = app_state
        self._build()
        self.state.result_changed.connect(self.refresh_from_state)

    def _build(self):
        root = QVBoxLayout(self)

        bar = QHBoxLayout()
        title = QLabel(t("Structural report")); title.setObjectName("h2")
        bar.addWidget(title); bar.addStretch()
        self.cb_ai = QCheckBox(t("Include AI review if generated"))
        self.cb_ai.setChecked(True)
        bar.addWidget(self.cb_ai)
        self.b_pdf = QPushButton(t("Export PDF..."))
        self.b_pdf.clicked.connect(self._export)
        bar.addWidget(self.b_pdf)
        root.addLayout(bar)

        self.hint = QLabel(t("Run an analysis to generate the report."))
        self.hint.setObjectName("hint")
        root.addWidget(self.hint)

        self.chips = QHBoxLayout()
        self.chips.setSpacing(8)
        chips_w = QWidget(); chips_w.setLayout(self.chips)
        root.addWidget(chips_w)

        self.text = QTextEdit(); self.text.setReadOnly(True)
        self.text.setStyleSheet("font-size: 12px; line-height: 1.5;")
        root.addWidget(self.text, 1)

        credit = QLabel(author_html()); credit.setOpenExternalLinks(True)
        credit.setTextFormat(Qt.RichText); credit.setAlignment(Qt.AlignRight)
        root.addWidget(credit)

    def _clear_chips(self):
        while self.chips.count():
            item = self.chips.takeAt(0)
            if item.widget():
                item.widget().deleteLater()

    def _add_chip(self, verdict):
        fg, bg, border = _CHIP.get(verdict.level, _CHIP["yellow"])
        f = QFrame()
        f.setStyleSheet(
            f"background:{bg}; border:1px solid {border}; border-radius:8px;")
        lay = QVBoxLayout(f); lay.setContentsMargins(10, 6, 10, 6); lay.setSpacing(0)
        top = QLabel(f"<b style='color:{fg}'>{verdict.tag}</b> &nbsp;"
                     f"<span style='color:#374151'>{verdict.value}</span>")
        top.setTextFormat(Qt.RichText)
        name = QLabel(verdict.name); name.setStyleSheet("color:#6b7280; font-size:10px;")
        lay.addWidget(top); lay.addWidget(name)
        self.chips.addWidget(f)

    def refresh_from_state(self):
        r = self.state.result
        if r is None:
            return
        self.hint.setText(t("This assessment is generated by StructVis without "
                            "AI. The AI Review tab can add a written second opinion."))
        self._clear_chips()
        for v in summary.verdicts(r, self.state.load_case):
            self._add_chip(v)
        self.chips.addStretch()

        mass = None
        if self.state.mesh is not None:
            mass = total_mass(self.state.mesh, self.state.params, half_wing=False)
        text = summary.plain_language(r, self.state.params, self.state.load_case,
                                      self.state.design, mass)
        html = "".join(f"<p>{p}</p>" for p in text.split("\n\n"))
        self.text.setHtml(html)

    # ------------------------------------------------------------------ PDF
    def _export(self):
        if self.state.result is None:
            QMessageBox.information(self, t("No results"),
                                    t("Run an analysis first.")); return
        default = "structvis_report.pdf"
        if self.state.project is not None:
            default = f"{self.state.project.model.name}_structural_report.pdf"
        fn, _ = QFileDialog.getSaveFileName(
            self, t("Export report"), default, t("PDF file (*.pdf)"))
        if not fn:
            return
        try:
            self._write_pdf(fn)
        except Exception as e:  # noqa: BLE001
            QMessageBox.critical(self, t("Report error"), str(e)); return
        self.state.status(t("Report saved: {}").format(Path(fn).name))
        if QMessageBox.question(
                self, t("Report saved"),
                t("Report exported to:\n{}\n\nOpen it now?").format(fn)) \
                == QMessageBox.Yes:
            import os
            try:
                os.startfile(fn)  # noqa: S606 (Windows)
            except Exception:  # noqa: BLE001
                pass

    def _write_pdf(self, fn):
        s = self.state
        sl = None
        if s.mesh is not None and s.project is not None:
            from ...core.mass import mass_per_station
            dp = s.design or resolve_design_point(s.project, s.load_case)
            sm = mass_per_station(s.mesh, s.params, s.mesh.y_stations)
            sl = strip_loads(s.project, s.load_case, s.mesh.y_stations,
                             s.params.front_spar, s.params.rear_spar, design=dp,
                             struct_mass_station=sm,
                             point_masses=getattr(s, "point_masses", None))
        mass = total_mass(s.mesh, s.params, half_wing=False) if s.mesh else None
        ai_text = None
        if self.cb_ai.isChecked():
            ai_text = getattr(s, "ai_review_text", None) or None
        thumb = self._grab_thumbnail()
        pdf_report.build_report(
            s.result, fn, project=s.project, params=s.params,
            load_case=s.load_case, design=s.design, strip_loads=sl,
            total_mass_kg=mass, ai_text=ai_text, thumbnail_png=thumb,
            buckling=s.buckling)

    def _grab_thumbnail(self):
        try:
            view = getattr(self.state.window.results_tab, "view", None)
            if view is not None:
                return view.screenshot_bytes()
        except Exception:  # noqa: BLE001
            pass
        return None
